import telebot

API_TOKEN = '7981021249:AAE9LtRJtTMViaB1uz-oH4tDREZo4aTpxA8'
bot = telebot.TeleBot(API_TOKEN)

user_data = {}

classes = [f'{i}{letter}' for i in range(1, 13) for letter in ['A', 'B', 'C', 'D', 'E', 'V']]

schedules = {
    'Dushanba': {
        '1A': "1-soat: Matematika\n2-soat: Ona tili\n3-soat: Ingliz tili",
        '1B': "1-soat: Matematika\n2-soat: Rus tili\n3-soat: Jismoniy tarbiya",
        '1C': "1-soat: Matematika\n2-soat: Ona tili\n3-soat: Jismoniy tarbiya",
        '1D': "1-soat: Matematika 08:00 - 08:45\n2-soat: Tarix 08:50 - 09:35",
        '1E': "1-soat: Tarix 08:00 - 08:45\n2-soat: Adabiyot 08:50 - 09:35",
        '1V': "1-soat: Matematika 08:00 - 08:45\n2-soat: Ingliz tili 08:50 - 09:35",
        '2A': "1-soat: Matematika 08:00 - 08:45\n2-soat: Ingliz tili 08:50 - 09:35",
        '2B': "1-soat: Tarix 08:00 - 08:45\n2-soat: Ona tili 08:50 - 09:35",
        '2C': "1-soat: Jismoniy tarbiya 08:00 - 08:45\n2-soat: Tabiiy fanlar 08:50 - 09:35",
        '2D': "1-soat: Biologiya 08:00 - 08:45\n2-soat: Kimyo 08:50 - 09:35",
        '2E': "1-soat: Fizika 08:00 - 08:45\n2-soat: Ingliz tili 08:50 - 09:35",
        '2V': "1-soat: Adabiyot 08:00 - 08:45\n2-soat: Matematika 08:50 - 09:35",
        '3A': "1-soat: Kimyo\n2-soat: Matematika\n3-soat: Tarix",
        '3B': "1-soat: Biologiya\n2-soat: Matematika\n3-soat: Ona tili",
        '3C': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Jismoniy tarbiya",
        '3D': "1-soat: Ona tili\n2-soat: Tarix\n3-soat: Matematika",
        '3E': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Kimyo",
        '3V': "1-soat: Matematika\n2-soat: Ingliz tili\n3-soat: Tarix",
        '4A': "1-soat: Biologiya\n2-soat: Kimyo\n3-soat: Tarix",
        '4B': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Ona tili",
        '4C': "1-soat: Matematika\n2-soat: Biologiya\n3-soat: Jismoniy tarbiya",
        '4D': "1-soat: Tarix\n2-soat: Matematika\n3-soat: Ingliz tili",
        '4E': "1-soat: Biologiya\n2-soat: Tarix\n3-soat: Adabiyot",
        '4V': "1-soat: Jismoniy tarbiya\n2-soat: Tarix\n3-soat: Matematika",
        '5A': "1-soat: Matematika\n2-soat: Ona tili\n3-soat: Tarix",
        '5B': "1-soat: Tarix\n2-soat: Matematika\n3-soat: Biologiya",
        '5C': "1-soat: Matematika\n2-soat: Kimyo\n3-soat: Biologiya",
        '5D': "1-soat: Biologiya\n2-soat: Matematika\n3-soat: Jismoniy tarbiya",
        '5E': "1-soat: Kimyo\n2-soat: Adabiyot\n3-soat: Tarix",
        '5V': "1-soat: Tarix\n2-soat: Matematika\n3-soat: Ingliz tili",
        '6A': "1-soat: Matematika\n2-soat: Biologiya\n3-soat: Tarix",
        '6B': "1-soat: Fizika\n2-soat: Matematika\n3-soat: Kimyo",
        '6C': "1-soat: Biologiya\n2-soat: Ingliz tili\n3-soat: Tarix",
        '6D': "1-soat: Tarix\n2-soat: Jismoniy tarbiya\n3-soat: Kimyo",
        '6E': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Biologiya",
        '6V': "1-soat: Fizika\n2-soat: Matematika\n3-soat: Ingliz tili",
        '7A': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Ona tili",
        '7B': "1-soat: Biologiya\n2-soat: Fizika\n3-soat: Matematika",
        '7C': "1-soat: Matematika\n2-soat: Kimyo\n3-soat: Tarix",
        '7D': "1-soat: Ona tili\n2-soat: Tarix\n3-soat: Matematika",
        '7E': "1-soat: Fizika\n2-soat: Biologiya\n3-soat: Adabiyot",
        '7V': "1-soat: Matematika\n2-soat: Adabiyot\n3-soat: Tarix",
        '8A': "1-soat: Biologiya\n2-soat: Kimyo\n3-soat: Tarix",
        '8B': "1-soat: Matematika\n2-soat: Fizika\n3-soat: Kimyo",
        '8C': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Jismoniy tarbiya",
        '8D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Biologiya",
        '8E': "1-soat: Jismoniy tarbiya\n2-soat: Tarix\n3-soat: Matematika",
        '8V': "1-soat: Biologiya\n2-soat: Matematika\n3-soat: Fizika",
        '9A': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
        '9B': "1-soat: Kimyo\n2-soat: Biologiya\n3-soat: Matematika",
        '9C': "1-soat: Fizika\n2-soat: Kimyo\n3-soat: Adabiyot",
        '9D': "1-soat: Biologiya\n2-soat: Tarix\n3-soat: Matematika",
        '9E': "1-soat: Matematika\n2-soat: Jismoniy tarbiya\n3-soat: Kimyo",
        '9V': "1-soat: Matematika\n2-soat: Fizika\n3-soat: Tarix",
        '10A': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Matematika",
        '10B': "1-soat: Matematika\n2-soat: Fizika\n3-soat: Tarix",
        '10C': "1-soat: Adabiyot\n2-soat: Matematika\n3-soat: Jismoniy tarbiya",
        '10D': "1-soat: Tarix\n2-soat: Kimyo\n3-soat: Biologiya",
        '10E': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Biologiya",
        '10V': "1-soat: Kimyo\n2-soat: Tarix\n3-soat: Matematika",
        '11A': "1-soat: Fizika\n2-soat: Matematika\n3-soat: Ingliz tili",
        '11B': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Biologiya",
        '11C': "1-soat: Jismoniy tarbiya\n2-soat: Kimyo\n3-soat: Tarix",
        '11D': "1-soat: Matematika\n2-soat: Adabiyot\n3-soat: Kimyo",
        '11E': "1-soat: Biologiya\n2-soat: Ingliz tili\n3-soat: Matematika",
        '11V': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
    },
    # Shu tarzda boshqa kunlarni ham kiritishingiz mumkin
}
schedules['Seshanba'] = {
    '1A': "1-soat: Biologiya\n2-soat: Kimyo\n3-soat: Tarix",
    '1B': "1-soat: Fizika\n2-soat: Matematika\n3-soat: Ona tili",
    '1C': "1-soat: Matematika\n2-soat: Ona tili\n3-soat: Jismoniy tarbiya",
    '1D': "1-soat: Matematika 08:00 - 08:45\n2-soat: Tarix 08:50 - 09:35",
    '1E': "1-soat: Tarix 08:00 - 08:45\n2-soat: Adabiyot 08:50 - 09:35",
    '1V': "1-soat: Matematika 08:00 - 08:45\n2-soat: Ingliz tili 08:50 - 09:35",
    '2A': "1-soat: Tarix 08:00 - 08:45\n2-soat: Ona tili 08:50 - 09:35",
    '2B': "1-soat: Matematika 08:00 - 08:45\n2-soat: Fizika 08:50 - 09:35",
    '2C': "1-soat: Jismoniy tarbiya 08:00 - 08:45\n2-soat: Tabiiy fanlar 08:50 - 09:35",
    '2D': "1-soat: Biologiya 08:00 - 08:45\n2-soat: Kimyo 08:50 - 09:35",
    '2E': "1-soat: Fizika 08:00 - 08:45\n2-soat: Ingliz tili 08:50 - 09:35",
    '2V': "1-soat: Adabiyot 08:00 - 08:45\n2-soat: Matematika 08:50 - 09:35",
    '3A': "1-soat: Tarix\n2-soat: Matematika\n3-soat: Biologiya",
    '3B': "1-soat: Matematika\n2-soat: Fizika\n3-soat: Kimyo",
    '3C': "1-soat: Matematika\n2-soat: Kimyo\n3-soat: Biologiya",
    '3D': "1-soat: Tarix\n2-soat: Matematika\n3-soat: Jismoniy tarbiya",
    '3E': "1-soat: Biologiya\n2-soat: Tarix\n3-soat: Adabiyot",
    '3V': "1-soat: Matematika\n2-soat: Fizika\n3-soat: Ingliz tili",
    '4A': "1-soat: Matematika\n2-soat: Biologiya\n3-soat: Tarix",
    '4B': "1-soat: Tarix\n2-soat: Jismoniy tarbiya\n3-soat: Biologiya",
    '4C': "1-soat: Biologiya\n2-soat: Tarix\n3-soat: Jismoniy tarbiya",
    '4D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Biologiya",
    '4E': "1-soat: Adabiyot\n2-soat: Kimyo\n3-soat: Biologiya",
    '4V': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
    '5A': "1-soat: Matematika\n2-soat: Biologiya\n3-soat: Kimyo",
    '5B': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Jismoniy tarbiya",
    '5C': "1-soat: Matematika\n2-soat: Biologiya\n3-soat: Tarix",
    '5D': "1-soat: Jismoniy tarbiya\n2-soat: Tarix\n3-soat: Matematika",
    '5E': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
    '5V': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Matematika",
    '6A': "1-soat: Matematika\n2-soat: Kimyo\n3-soat: Tarix",
    '6B': "1-soat: Fizika\n2-soat: Tarix\n3-soat: Biologiya",
    '6C': "1-soat: Tarix\n2-soat: Jismoniy tarbiya\n3-soat: Kimyo",
    '6D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
    '6E': "1-soat: Biologiya\n2-soat: Tarix\n3-soat: Matematika",
    '6V': "1-soat: Tarix\n2-soat: Jismoniy tarbiya\n3-soat: Matematika",
    '7A': "1-soat: Matematika\n2-soat: Jismoniy tarbiya\n3-soat: Adabiyot",
    '7B': "1-soat: Fizika\n2-soat: Matematika\n3-soat: Kimyo",
    '7C': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Kimyo",
    '7D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
    '7E': "1-soat: Adabiyot\n2-soat: Biologiya\n3-soat: Matematika",
    '7V': "1-soat: Jismoniy tarbiya\n2-soat: Tarix\n3-soat: Matematika",
    '8A': "1-soat: Tarix\n2-soat: Matematika\n3-soat: Kimyo",
    '8B': "1-soat: Fizika\n2-soat: Matematika\n3-soat: Biologiya",
    '8C': "1-soat: Biologiya\n2-soat: Kimyo\n3-soat: Matematika",
    '8D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Jismoniy tarbiya",
    '8E': "1-soat: Tarix\n2-soat: Adabiyot\n3-soat: Biologiya",
    '8V': "1-soat: Jismoniy tarbiya\n2-soat: Tarix\n3-soat: Biologiya",
    '9A': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Biologiya",
    '9B': "1-soat: Kimyo\n2-soat: Tarix\n3-soat: Matematika",
    '9C': "1-soat: Matematika\n2-soat: Jismoniy tarbiya\n3-soat: Tarix",
    '9D': "1-soat: Fizika\n2-soat: Matematika\n3-soat: Biologiya",
    '9E': "1-soat: Tarix\n2-soat: Matematika\n3-soat: Kimyo",
    '9V': "1-soat: Kimyo\n2-soat: Matematika\n3-soat: Biologiya",
    '10A': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Fizika",
    '10B': "1-soat: Matematika\n2-soat: Kimyo\n3-soat: Tarix",
    '10C': "1-soat: Tarix\n2-soat: Kimyo\n3-soat: Matematika",
    '10D': "1-soat: Biologiya\n2-soat: Adabiyot\n3-soat: Matematika",
    '10E': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Adabiyot",
    '10V': "1-soat: Kimyo\n2-soat: Tarix\n3-soat: Biologiya",
    '11A': "1-soat: Matematika\n2-soat: Kimyo\n3-soat: Tarix",
    '11B': "1-soat: Biologiya\n2-soat: Tarix\n3-soat: Jismoniy tarbiya",
    '11C': "1-soat: Matematika\n2-soat: Ingliz tili\n3-soat: Kimyo",
    '11D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Adabiyot",
    '11E': "1-soat: Biologiya\n2-soat: Ingliz tili\n3-soat: Matematika",
    '11V': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
}
schedules['Chorshanba'] = {
    '1A': "1-soat: Fizika\n2-soat: Tarix\n3-soat: Ona tili",
    '1B': "1-soat: Matematika\n2-soat: Biologiya\n3-soat: Jismoniy tarbiya",
    '1C': "1-soat: Ingliz tili\n2-soat: Matematika\n3-soat: Tarix",
    '1D': "1-soat: Ona tili 08:00 - 08:45\n2-soat: Tarix 08:50 - 09:35",
    '1E': "1-soat: Tarix 08:00 - 08:45\n2-soat: Biologiya 08:50 - 09:35",
    '1V': "1-soat: Matematika 08:00 - 08:45\n2-soat: Jismoniy tarbiya 08:50 - 09:35",
    '2A': "1-soat: Matematika 08:00 - 08:45\n2-soat: Ona tili 08:50 - 09:35",
    '2B': "1-soat: Tarix 08:00 - 08:45\n2-soat: Biologiya 08:50 - 09:35",
    '2C': "1-soat: Jismoniy tarbiya 08:00 - 08:45\n2-soat: Kimyo 08:50 - 09:35",
    '2D': "1-soat: Fizika 08:00 - 08:45\n2-soat: Matematika 08:50 - 09:35",
    '2E': "1-soat: Tarix 08:00 - 08:45\n2-soat: Ona tili 08:50 - 09:35",
    '2V': "1-soat: Adabiyot 08:00 - 08:45\n2-soat: Matematika 08:50 - 09:35",
    '3A': "1-soat: Fizika\n2-soat: Tarix\n3-soat: Matematika",
    '3B': "1-soat: Matematika\n2-soat: Biologiya\n3-soat: Kimyo",
    '3C': "1-soat: Matematika\n2-soat: Kimyo\n3-soat: Biologiya",
    '3D': "1-soat: Tarix\n2-soat: Matematika\n3-soat: Jismoniy tarbiya",
    '3E': "1-soat: Biologiya\n2-soat: Tarix\n3-soat: Adabiyot",
    '3V': "1-soat: Matematika\n2-soat: Fizika\n3-soat: Ingliz tili",
    '4A': "1-soat: Matematika\n2-soat: Biologiya\n3-soat: Tarix",
    '4B': "1-soat: Tarix\n2-soat: Jismoniy tarbiya\n3-soat: Biologiya",
    '4C': "1-soat: Biologiya\n2-soat: Tarix\n3-soat: Jismoniy tarbiya",
    '4D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Biologiya",
    '4E': "1-soat: Adabiyot\n2-soat: Kimyo\n3-soat: Biologiya",
    '4V': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
    '5A': "1-soat: Matematika\n2-soat: Biologiya\n3-soat: Kimyo",
    '5B': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Jismoniy tarbiya",
    '5C': "1-soat: Matematika\n2-soat: Biologiya\n3-soat: Tarix",
    '5D': "1-soat: Jismoniy tarbiya\n2-soat: Tarix\n3-soat: Matematika",
    '5E': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
    '5V': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Matematika",
    '6A': "1-soat: Matematika\n2-soat: Kimyo\n3-soat: Tarix",
    '6B': "1-soat: Fizika\n2-soat: Tarix\n3-soat: Biologiya",
    '6C': "1-soat: Tarix\n2-soat: Jismoniy tarbiya\n3-soat: Kimyo",
    '6D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
    '6E': "1-soat: Biologiya\n2-soat: Tarix\n3-soat: Matematika",
    '6V': "1-soat: Tarix\n2-soat: Jismoniy tarbiya\n3-soat: Matematika",
    '7A': "1-soat: Matematika\n2-soat: Jismoniy tarbiya\n3-soat: Adabiyot",
    '7B': "1-soat: Fizika\n2-soat: Matematika\n3-soat: Kimyo",
    '7C': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Kimyo",
    '7D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
    '7E': "1-soat: Adabiyot\n2-soat: Biologiya\n3-soat: Matematika",
    '7V': "1-soat: Jismoniy tarbiya\n2-soat: Tarix\n3-soat: Matematika",
    '8A': "1-soat: Tarix\n2-soat: Matematika\n3-soat: Kimyo",
    '8B': "1-soat: Fizika\n2-soat: Matematika\n3-soat: Biologiya",
    '8C': "1-soat: Biologiya\n2-soat: Kimyo\n3-soat: Matematika",
    '8D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Jismoniy tarbiya",
    '8E': "1-soat: Tarix\n2-soat: Adabiyot\n3-soat: Biologiya",
    '8V': "1-soat: Jismoniy tarbiya\n2-soat: Tarix\n3-soat: Biologiya",
    '9A': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Biologiya",
    '9B': "1-soat: Kimyo\n2-soat: Tarix\n3-soat: Matematika",
    '9C': "1-soat: Matematika\n2-soat: Jismoniy tarbiya\n3-soat: Tarix",
    '9D': "1-soat: Fizika\n2-soat: Matematika\n3-soat: Biologiya",
    '9E': "1-soat: Tarix\n2-soat: Matematika\n3-soat: Kimyo",
    '9V': "1-soat: Kimyo\n2-soat: Matematika\n3-soat: Biologiya",
    '10A': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Fizika",
    '10B': "1-soat: Matematika\n2-soat: Kimyo\n3-soat: Tarix",
    '10C': "1-soat: Tarix\n2-soat: Kimyo\n3-soat: Matematika",
    '10D': "1-soat: Biologiya\n2-soat: Adabiyot\n3-soat: Matematika",
    '10E': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Adabiyot",
    '10V': "1-soat: Kimyo\n2-soat: Tarix\n3-soat: Biologiya",
    '11A': "1-soat: Matematika\n2-soat: Kimyo\n3-soat: Tarix",
    '11B': "1-soat: Biologiya\n2-soat: Tarix\n3-soat: Jismoniy tarbiya",
    '11C': "1-soat: Matematika\n2-soat: Ingliz tili\n3-soat: Kimyo",
    '11D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Adabiyot",
    '11E': "1-soat: Matematika\n2-soat: Fizika\n3-soat: Tarix",
    '11V': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
}
schedules['Payshanba'] = {
    '1A': "1-soat: Matematika\n2-soat: Ona tili\n3-soat: Tarix",
    '1B': "1-soat: Biologiya\n2-soat: Fizika\n3-soat: Jismoniy tarbiya",
    '1C': "1-soat: Ingliz tili\n2-soat: Tarix\n3-soat: Matematika",
    '1D': "1-soat: Ona tili 08:00 - 08:45\n2-soat: Matematika 08:50 - 09:35",
    '1E': "1-soat: Tarix 08:00 - 08:45\n2-soat: Biologiya 08:50 - 09:35",
    '1V': "1-soat: Matematika 08:00 - 08:45\n2-soat: Jismoniy tarbiya 08:50 - 09:35",
    '2A': "1-soat: Matematika 08:00 - 08:45\n2-soat: Ona tili 08:50 - 09:35",
    '2B': "1-soat: Tarix 08:00 - 08:45\n2-soat: Biologiya 08:50 - 09:35",
    '2C': "1-soat: Jismoniy tarbiya 08:00 - 08:45\n2-soat: Kimyo 08:50 - 09:35",
    '2D': "1-soat: Fizika 08:00 - 08:45\n2-soat: Matematika 08:50 - 09:35",
    '2E': "1-soat: Tarix 08:00 - 08:45\n2-soat: Ona tili 08:50 - 09:35",
    '2V': "1-soat: Adabiyot 08:00 - 08:45\n2-soat: Matematika 08:50 - 09:35",
    '3A': "1-soat: Fizika\n2-soat: Matematika\n3-soat: Kimyo",
    '3B': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Matematika",
    '3C': "1-soat: Matematika\n2-soat: Kimyo\n3-soat: Jismoniy tarbiya",
    '3D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Biologiya",
    '3E': "1-soat: Biologiya\n2-soat: Tarix\n3-soat: Adabiyot",
    '3V': "1-soat: Matematika\n2-soat: Fizika\n3-soat: Ingliz tili",
    '4A': "1-soat: Matematika\n2-soat: Biologiya\n3-soat: Tarix",
    '4B': "1-soat: Tarix\n2-soat: Jismoniy tarbiya\n3-soat: Biologiya",
    '4C': "1-soat: Biologiya\n2-soat: Tarix\n3-soat: Jismoniy tarbiya",
    '4D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Biologiya",
    '4E': "1-soat: Adabiyot\n2-soat: Kimyo\n3-soat: Biologiya",
    '4V': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
    '5A': "1-soat: Matematika\n2-soat: Biologiya\n3-soat: Kimyo",
    '5B': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Jismoniy tarbiya",
    '5C': "1-soat: Matematika\n2-soat: Biologiya\n3-soat: Tarix",
    '5D': "1-soat: Jismoniy tarbiya\n2-soat: Tarix\n3-soat: Matematika",
    '5E': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
    '5V': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Matematika",
    '6A': "1-soat: Matematika\n2-soat: Kimyo\n3-soat: Tarix",
    '6B': "1-soat: Fizika\n2-soat: Tarix\n3-soat: Biologiya",
    '6C': "1-soat: Tarix\n2-soat: Jismoniy tarbiya\n3-soat: Kimyo",
    '6D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
    '6E': "1-soat: Biologiya\n2-soat: Tarix\n3-soat: Matematika",
    '6V': "1-soat: Tarix\n2-soat: Jismoniy tarbiya\n3-soat: Matematika",
    '7A': "1-soat: Matematika\n2-soat: Jismoniy tarbiya\n3-soat: Adabiyot",
    '7B': "1-soat: Fizika\n2-soat: Matematika\n3-soat: Kimyo",
    '7C': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Kimyo",
    '7D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
    '7E': "1-soat: Adabiyot\n2-soat: Biologiya\n3-soat: Matematika",
    '7V': "1-soat: Jismoniy tarbiya\n2-soat: Tarix\n3-soat: Matematika",
    '8A': "1-soat: Tarix\n2-soat: Matematika\n3-soat: Kimyo",
    '8B': "1-soat: Fizika\n2-soat: Matematika\n3-soat: Biologiya",
    '8C': "1-soat: Biologiya\n2-soat: Kimyo\n3-soat: Matematika",
    '8D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Jismoniy tarbiya",
    '8E': "1-soat: Tarix\n2-soat: Adabiyot\n3-soat: Biologiya",
    '8V': "1-soat: Jismoniy tarbiya\n2-soat: Tarix\n3-soat: Biologiya",
    '9A': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Biologiya",
    '9B': "1-soat: Kimyo\n2-soat: Tarix\n3-soat: Matematika",
    '9C': "1-soat: Matematika\n2-soat: Jismoniy tarbiya\n3-soat: Tarix",
    '9D': "1-soat: Fizika\n2-soat: Matematika\n3-soat: Biologiya",
    '9E': "1-soat: Tarix\n2-soat: Matematika\n3-soat: Kimyo",
    '9V': "1-soat: Kimyo\n2-soat: Matematika\n3-soat: Biologiya",
    '10A': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Fizika",
    '10B': "1-soat: Matematika\n2-soat: Kimyo\n3-soat: Tarix",
    '10C': "1-soat: Tarix\n2-soat: Kimyo\n3-soat: Matematika",
    '10D': "1-soat: Biologiya\n2-soat: Adabiyot\n3-soat: Matematika",
    '10E': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Adabiyot",
    '10V': "1-soat: Kimyo\n2-soat: Tarix\n3-soat: Biologiya",
    '11A': "1-soat: Matematika\n2-soat: Kimyo\n3-soat: Tarix",
    '11B': "1-soat: Biologiya\n2-soat: Tarix\n3-soat: Jismoniy tarbiya",
    '11C': "1-soat: Matematika\n2-soat: Ingliz tili\n3-soat: Kimyo",
    '11D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Adabiyot",
    '11E': "1-soat: Biologiya\n2-soat: Tarix\n3-soat: Jismoniy tarbiya",
    '11V': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
}

schedules['Juma'] = {
    '1A': "1-soat: Matematika\n2-soat: Ona tili\n3-soat: Ingliz tili",
    '1B': "1-soat: Tarix\n2-soat: Jismoniy tarbiya\n3-soat: Biologiya",
    '1C': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Ona tili",
    '1D': "1-soat: Fizika 08:00 - 08:45\n2-soat: Kimyo 08:50 - 09:35",
    '1E': "1-soat: Tarix 08:00 - 08:45\n2-soat: Matematika 08:50 - 09:35",
    '1V': "1-soat: Jismoniy tarbiya 08:00 - 08:45\n2-soat: Tarix 08:50 - 09:35",
    '2A': "1-soat: Matematika 08:00 - 08:45\n2-soat: Ona tili 08:50 - 09:35",
    '2B': "1-soat: Tarix 08:00 - 08:45\n2-soat: Jismoniy tarbiya 08:50 - 09:35",
    '2C': "1-soat: Jismoniy tarbiya 08:00 - 08:45\n2-soat: Biologiya 08:50 - 09:35",
    '2D': "1-soat: Fizika 08:00 - 08:45\n2-soat: Matematika 08:50 - 09:35",
    '2E': "1-soat: Tarix 08:00 - 08:45\n2-soat: Matematika 08:50 - 09:35",
    '2V': "1-soat: Kimyo 08:00 - 08:45\n2-soat: Jismoniy tarbiya 08:50 - 09:35",
    '3A': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Matematika",
    '3B': "1-soat: Kimyo\n2-soat: Tarix\n3-soat: Matematika",
    '3C': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Jismoniy tarbiya",
    '3D': "1-soat: Fizika\n2-soat: Matematika\n3-soat: Biologiya",
    '3E': "1-soat: Tarix\n2-soat: Kimyo\n3-soat: Biologiya",
    '3V': "1-soat: Matematika\n2-soat: Kimyo\n3-soat: Tarix",
    '4A': "1-soat: Matematika\n2-soat: Biologiya\n3-soat: Tarix",
    '4B': "1-soat: Tarix\n2-soat: Jismoniy tarbiya\n3-soat: Biologiya",
    '4C': "1-soat: Biologiya\n2-soat: Tarix\n3-soat: Jismoniy tarbiya",
    '4D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Biologiya",
    '4E': "1-soat: Adabiyot\n2-soat: Kimyo\n3-soat: Biologiya",
    '4V': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
    '5A': "1-soat: Matematika\n2-soat: Biologiya\n3-soat: Kimyo",
    '5B': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Jismoniy tarbiya",
    '5C': "1-soat: Matematika\n2-soat: Biologiya\n3-soat: Tarix",
    '5D': "1-soat: Jismoniy tarbiya\n2-soat: Tarix\n3-soat: Matematika",
    '5E': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
    '5V': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Matematika",
    '6A': "1-soat: Matematika\n2-soat: Kimyo\n3-soat: Tarix",
    '6B': "1-soat: Fizika\n2-soat: Tarix\n3-soat: Biologiya",
    '6C': "1-soat: Tarix\n2-soat: Jismoniy tarbiya\n3-soat: Kimyo",
    '6D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
    '6E': "1-soat: Biologiya\n2-soat: Tarix\n3-soat: Matematika",
    '6V': "1-soat: Tarix\n2-soat: Jismoniy tarbiya\n3-soat: Matematika",
    '7A': "1-soat: Matematika\n2-soat: Jismoniy tarbiya\n3-soat: Adabiyot",
    '7B': "1-soat: Fizika\n2-soat: Matematika\n3-soat: Kimyo",
    '7C': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Kimyo",
    '7D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
    '7E': "1-soat: Adabiyot\n2-soat: Biologiya\n3-soat: Matematika",
    '7V': "1-soat: Jismoniy tarbiya\n2-soat: Tarix\n3-soat: Matematika",
    '8A': "1-soat: Tarix\n2-soat: Matematika\n3-soat: Kimyo",
    '8B': "1-soat: Fizika\n2-soat: Matematika\n3-soat: Biologiya",
    '8C': "1-soat: Biologiya\n2-soat: Kimyo\n3-soat: Matematika",
    '8D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Jismoniy tarbiya",
    '8E': "1-soat: Tarix\n2-soat: Adabiyot\n3-soat: Biologiya",
    '8V': "1-soat: Jismoniy tarbiya\n2-soat: Tarix\n3-soat: Biologiya",
    '9A': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Biologiya",
    '9B': "1-soat: Kimyo\n2-soat: Tarix\n3-soat: Matematika",
    '9C': "1-soat: Matematika\n2-soat: Jismoniy tarbiya\n3-soat: Tarix",
    '9D': "1-soat: Fizika\n2-soat: Matematika\n3-soat: Biologiya",
    '9E': "1-soat: Tarix\n2-soat: Matematika\n3-soat: Kimyo",
    '9V': "1-soat: Kimyo\n2-soat: Matematika\n3-soat: Biologiya",
    '10A': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Fizika",
    '10B': "1-soat: Matematika\n2-soat: Kimyo\n3-soat: Tarix",
    '10C': "1-soat: Tarix\n2-soat: Kimyo\n3-soat: Matematika",
    '10D': "1-soat: Biologiya\n2-soat: Adabiyot\n3-soat: Matematika",
    '10E': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Adabiyot",
    '10V': "1-soat: Kimyo\n2-soat: Tarix\n3-soat: Biologiya",
    '11A': "1-soat: Matematika\n2-soat: Kimyo\n3-soat: Tarix",
    '11B': "1-soat: Biologiya\n2-soat: Tarix\n3-soat: Jismoniy tarbiya",
    '11C': "1-soat: Matematika\n2-soat: Ingliz tili\n3-soat: Kimyo",
    '11D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Adabiyot",
    '11E': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Biologiya",
    '11V': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
}
schedules['Shanba'] = {
    '1A': "1-soat: Matematika\n2-soat: Ona tili\n3-soat: Ingliz tili",
    '1B': "1-soat: Tarix\n2-soat: Jismoniy tarbiya\n3-soat: Biologiya",
    '1C': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Ona tili",
    '1D': "1-soat: Fizika 08:00 - 08:45\n2-soat: Kimyo 08:50 - 09:35",
    '1E': "1-soat: Tarix 08:00 - 08:45\n2-soat: Matematika 08:50 - 09:35",
    '1V': "1-soat: Jismoniy tarbiya 08:00 - 08:45\n2-soat: Tarix 08:50 - 09:35",
    '2A': "1-soat: Matematika 08:00 - 08:45\n2-soat: Ona tili 08:50 - 09:35",
    '2B': "1-soat: Tarix 08:00 - 08:45\n2-soat: Jismoniy tarbiya 08:50 - 09:35",
    '2C': "1-soat: Jismoniy tarbiya 08:00 - 08:45\n2-soat: Biologiya 08:50 - 09:35",
    '2D': "1-soat: Fizika 08:00 - 08:45\n2-soat: Matematika 08:50 - 09:35",
    '2E': "1-soat: Tarix 08:00 - 08:45\n2-soat: Matematika 08:50 - 09:35",
    '2V': "1-soat: Kimyo 08:00 - 08:45\n2-soat: Jismoniy tarbiya 08:50 - 09:35",
    '3A': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Matematika",
    '3B': "1-soat: Kimyo\n2-soat: Tarix\n3-soat: Matematika",
    '3C': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Jismoniy tarbiya",
    '3D': "1-soat: Fizika\n2-soat: Matematika\n3-soat: Biologiya",
    '3E': "1-soat: Tarix\n2-soat: Kimyo\n3-soat: Biologiya",
    '3V': "1-soat: Matematika\n2-soat: Kimyo\n3-soat: Tarix",
    '4A': "1-soat: Matematika\n2-soat: Biologiya\n3-soat: Tarix",
    '4B': "1-soat: Tarix\n2-soat: Jismoniy tarbiya\n3-soat: Biologiya",
    '4C': "1-soat: Biologiya\n2-soat: Tarix\n3-soat: Jismoniy tarbiya",
    '4D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Biologiya",
    '4E': "1-soat: Adabiyot\n2-soat: Kimyo\n3-soat: Biologiya",
    '4V': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
    '5A': "1-soat: Matematika\n2-soat: Biologiya\n3-soat: Kimyo",
    '5B': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Jismoniy tarbiya",
    '5C': "1-soat: Matematika\n2-soat: Biologiya\n3-soat: Tarix",
    '5D': "1-soat: Jismoniy tarbiya\n2-soat: Tarix\n3-soat: Matematika",
    '5E': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
    '5V': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Matematika",
    '6A': "1-soat: Matematika\n2-soat: Kimyo\n3-soat: Tarix",
    '6B': "1-soat: Fizika\n2-soat: Tarix\n3-soat: Biologiya",
    '6C': "1-soat: Tarix\n2-soat: Jismoniy tarbiya\n3-soat: Kimyo",
    '6D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
    '6E': "1-soat: Biologiya\n2-soat: Tarix\n3-soat: Matematika",
    '6V': "1-soat: Tarix\n2-soat: Jismoniy tarbiya\n3-soat: Matematika",
    '7A': "1-soat: Matematika\n2-soat: Jismoniy tarbiya\n3-soat: Adabiyot",
    '7B': "1-soat: Fizika\n2-soat: Matematika\n3-soat: Kimyo",
    '7C': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Kimyo",
    '7D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
    '7E': "1-soat: Adabiyot\n2-soat: Biologiya\n3-soat: Matematika",
    '7V': "1-soat: Jismoniy tarbiya\n2-soat: Tarix\n3-soat: Matematika",
    '8A': "1-soat: Tarix\n2-soat: Matematika\n3-soat: Kimyo",
    '8B': "1-soat: Fizika\n2-soat: Matematika\n3-soat: Biologiya",
    '8C': "1-soat: Biologiya\n2-soat: Kimyo\n3-soat: Matematika",
    '8D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Jismoniy tarbiya",
    '8E': "1-soat: Tarix\n2-soat: Adabiyot\n3-soat: Biologiya",
    '8V': "1-soat: Jismoniy tarbiya\n2-soat: Tarix\n3-soat: Biologiya",
    '9A': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Biologiya",
    '9B': "1-soat: Kimyo\n2-soat: Tarix\n3-soat: Matematika",
    '9C': "1-soat: Matematika\n2-soat: Jismoniy tarbiya\n3-soat: Tarix",
    '9D': "1-soat: Fizika\n2-soat: Matematika\n3-soat: Biologiya",
    '9E': "1-soat: Tarix\n2-soat: Matematika\n3-soat: Kimyo",
    '9V': "1-soat: Kimyo\n2-soat: Matematika\n3-soat: Biologiya",
    '10A': "1-soat: Tarix\n2-soat: Biologiya\n3-soat: Fizika",
    '10B': "1-soat: Matematika\n2-soat: Kimyo\n3-soat: Tarix",
    '10C': "1-soat: Tarix\n2-soat: Kimyo\n3-soat: Matematika",
    '10D': "1-soat: Biologiya\n2-soat: Adabiyot\n3-soat: Matematika",
    '10E': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Adabiyot",
    '10V': "1-soat: Kimyo\n2-soat: Tarix\n3-soat: Biologiya",
    '11A': "1-soat: Matematika\n2-soat: Kimyo\n3-soat: Tarix",
    '11B': "1-soat: Biologiya\n2-soat: Tarix\n3-soat: Jismoniy tarbiya",
    '11C': "1-soat: Matematika\n2-soat: Ingliz tili\n3-soat: Kimyo",
    '11D': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Adabiyot",
    '11E': "1-soat: Tarix\n2-soat: Jismoniy tarbiya\n3-soat: Biologiya",
    '11V': "1-soat: Matematika\n2-soat: Tarix\n3-soat: Kimyo",
}


@bot.message_handler(commands=['start'])
def start_message(message):
    bot.send_message(message.chat.id, "Asalomu alaykum! Sinfingizni kiriting (masalan: 1A, 5B, 11D):")
    bot.register_next_step_handler(message, ask_class)


def ask_class(message):
    sinf = message.text.upper()
    if sinf in classes:
        user_data[message.chat.id] = {'class': sinf}
        bot.send_message(message.chat.id, f"Rahmat! Sinfingiz {sinf}. Endi haftaning kunini tanlang.")
        show_week_days(message)
    else:
        bot.send_message(message.chat.id, "Iltimos, to'g'ri sinf kiriting (masalan: 1A, 2B, 11C).")
        bot.register_next_step_handler(message, ask_class)


def show_week_days(message):
    week_days = ['Dushanba', 'Seshanba', 'Chorshanba', 'Payshanba', 'Juma', 'Shanba']
    markup = telebot.types.ReplyKeyboardMarkup(one_time_keyboard=True, resize_keyboard=True)
    for day in week_days:
        markup.add(day)
    bot.send_message(message.chat.id, "Kunini tanlang:", reply_markup=markup)
    bot.register_next_step_handler(message, send_schedule)


def send_schedule(message):
    sinf = user_data[message.chat.id]['class']
    selected_day = message.text.capitalize()

    if selected_day in schedules:
        day_schedule = schedules[selected_day]
        response = day_schedule.get(sinf, "Bu kun uchun jadval mavjud emas.")
    else:
        response = "Bu kun uchun jadval mavjud emas."

    bot.send_message(message.chat.id, response)


bot.polling()
